checks:
  duplicate:
    enabled: true
    exclude_patterns:
      - "test/"
      - "examples/"
  structure:
    enabled: true
    exclude_patterns:
      - "cmake/"
      - "test/"
      - "examples/"

plugins:
  editorconfig:
    enabled: false
    config:
      editorconfig: .editorconfig
    exclude_patterns:
      - ".clangd/"
      - ".cache/"
  pylint:
    enabled: false
    exclude_patterns:
      - "cmake"
      - "doc"
      - "test/test_fe_engine/py_engine/py_engine.py"
      - "test/ci"
    PYTHONPATH:
      - python
      - build/python
  pep8:
    enabled: true
    exclude_patterns:
      - "test/test_fe_engine/py_engine/py_engine.py"
  cppcheck:
    enabled: false
    project: build/compile_commands.json
    language: c++
    check: warning, style, performance
    stds: [c++17]
    exclude_patterns:
      - "python/"

  fixme:
    enabled: true
    exclude_patterns:
      - "doc/"
exclude_patterns:
  - "third-party/"
  - "build*/"
