.builds:
  stage: build
  allow_failure: true
  variables:
    BLA_VENDOR = 'OpenBLAS'
  script:
    - mkdir build
    - cd build
    - cmake -DAKANTU_COHESIVE_ELEMENT:BOOL=TRUE \
                 -DAKANTU_IMPLICIT:BOOL=TRUE \
                 -DAKANTU_PARALLEL:BOOL=TRUE \
                 -DAKANTU_STRUCTURAL_MECHANICS:BOOL=TRUE \
                 -DAKANTU_HEAT_TRANSFER:BOOL=TRUE \
                 -DAKANTU_DAMAGE_NON_LOCAL:BOOL=TRUE \
                 -DAKANTU_PYTHON_INTERFACE:BOOL=TRUE \
                 -DAKANTU_EXAMPLES:BOOL=TRUE \
                 -DAKANTU_BUILD_ALL_EXAMPLES:BOOL=TRUE \
                 -DAKANTU_TEST_EXAMPLES:BOOL=FALSE \
                 -DAKANTU_TESTS:BOOL=TRUE \
                 -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo ..
    - make
  artifacts:
    paths:
      - build
    expire_in: 1 day

build:debian_testing_gcc:
  extends: .builds
  image: registry.gitlab.com/akantu/akantu:debian-testing

.tests:
  stage: test
  vatiables:
    OMPI_MCA_plm = 'isolated'
    OMPI_MCA_btl = 'tcp,self'

  script:
    - cd build
    - ctest -T test --no-compress-output --timeout 120 || true
    - tag=$(head -n 1 < Testing/TAG) if [ -e Testing/${tag}/Test.xml ]; then;  cp Testing/${tag}/Test.xml ./CTestResults.xml; fi
  artifacts:
    when: always
    paths:
      - build/CTestsResults.xml

test:debian_testing_gcc:
  image: registry.gitlab.com/akantu/akantu:debian-testing
  extends: .tests
  dependencies:
    - build:debian_testing_gcc
