tasks:
  - name: install dependencies
    init: sudo apt install cmake libboost-dev libopenblas-dev
  - name: configure
    command: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -S . -B build

vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd
    - cheshirekow.cmake-format
    - dracula-theme.theme-dracula
