tasks:
  - name: configure
    init: sudo apt -y install cmake libboost-dev libopenblas-dev gfortran
    command: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -S . -B build
    env:
      DEBIAN_FRONTEND: noninteractive

vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd
    - cheshirekow.cmake-format
    - dracula-theme.theme-dracula
    - ms-azuretools.vscode-docker
