# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: doc/dev-doc/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - python3-breathe
    - python3-git
    - python3-jinja2
    - python3-myst-parser
    - python3-sphinx
    - python3-sphinx-copybutton
    - python3-sphinx-rtd-theme
    - python3-sphinxcontrib.bibtex
    - python3-urllib3

# python:
#   install:
#     - requirements: doc/dev-doc/requirements.txt
